# Meta Data for SEO

## Homepage
title = "PG"
titleSeparator = "-"
titleAddition = "Software Engineer"
description = "Backend Engineer at FamPay. He is highly skilled in Django, RDBMS, AWS, DevOps. He has lead implementation of data science and backend systems."

## Open Graph + Twitter Cards
twitterSite = "henkverlinde"
twitterCreator = "henkverlinde"
facebookAuthor = "verlinde.henk"
facebookPublisher = "verlinde.henk"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
# schemaLogo = "logo-doks.png"
schemaTwitter = "https://twitter.com/pratikgajjar_in"
schemaLinkedIn = "https://www.linkedin.com/in/pratikgajjar/"
schemaGitHub = "https://github.com/pratikgajjar"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Pratik Gajjar Â© <script>document.write(new Date().getFullYear())</script>"

# Edit Page
docsRepo = "https://github.com/pratikgajjar/pg.in"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = false
  breadCrumb = false
  highLight = true
  kaTex = false
